### ISSUE TITLE
✂️  Remove Mint/Burn Events

### ISSUE THREAD

**Issue by z0r0z** [ricobank/gemfab#102]
Most dapps expect `Transfer()` with address(0) as flag for mint or burn. This will help adoption of gem and reduce code.

**Comment by kbrav** [comment]
This is tricky because with ERC-5679 `Transfer(x, 0, y)` can be emitted on either `transfer*` or `burn`.  We already have a slight deviation from the spec in that we allow binary approval so the general vibe is "if it's important, we can change it".  Still thinking though

**Comment by kbrav** [comment]
At least `Transfer()` on `mint` is fine...and the ERC20 spec `SHOULD` doesn't discuss burns

**Comment by kbrav** [comment]
Fixed, thx much @z0r0z

**Comment by z0r0z** [comment]
woo!
