### ISSUE TITLE
Make gas comparison table to other token implementations (see if our savings buy us a Caller event)

### ISSUE THREAD

**Issue by nmushegian** [ricobank/gemfab#70]
Particularly to Dai, which treats approve(-1) as infinite and saves a store
See if we are still cheapest if we also track caller event:  https://github.com/ricobank/gemfab/pull/67/files
If we aren't, decide if it's worth it

**Comment by kbrav** [comment]
[gem-dai-gas - Sheet1.pdf](https://github.com/ricobank/gemfab/files/8148254/gem-dai-gas.-.Sheet1.pdf)

[gem-dai-gas.csv](https://github.com/ricobank/gemfab/files/8148255/gem-dai-gas.csv)

Looks like Dai is faster for most transferFrom cases with and without caller event, by a couple thousand gas.  See https://github.com/kbrav/gemfab/tree/compare-dai

**Comment by nmushegian** [comment]
I don't understand how dai is cheaper even without the caller event
I thought we started with essentially dai and made only changes that decreased gas, other than caller event
What else could solidity be inserting in the newer versions other than value check (skipped with `payable` and its barely any gas anyway)

**Comment by nmushegian** [comment]
(Regardless of the final outcome, these relative costs are fine and we should keep Caller, imo)

**Comment by kbrav** [comment]
[gem-dai-gas.csv](https://github.com/ricobank/gemfab/files/8150204/gem-dai-gas.csv)
![image](https://user-images.githubusercontent.com/3114369/155915531-a123e870-d096-4d31-a108-195bc4a7a52e.png)

The refactored tests didn't work with tokens that treat allowance(a, a) == inf, so dai was skipping the block at `usr != msg.sender`.  It looks better now

**Comment by nmushegian** [comment]
Unfortunately I think we no longer can claim gas supremacy bc we gonna add ability to halt balances, some tokens really need that
