### ISSUE TITLE
see if making `name` and `symbol` a `bytes32` breaks common read use cases

### ISSUE THREAD

**Issue by nmushegian** [ricobank/gemfab#84]
If possible it would be nice to make these `bytes32` so that it dmap auto registration thing is less annoying

Because return values are not part of ABI, it should be accessible with the same call
But possibly interpreting the return value might give weird results, we should test it out and see what etherscan shows for bytes32 symbols

**Comment by dmfxyz** [comment]
it looks like at least etherscan will pick up bytes32. See here:

Verified Gem Address (modified to bytes32 name and bytes32 symbol): 
https://rinkeby.etherscan.io/address/0x5Fe371CcB3C0dc8718B7c0470600A230d6c2eB45#code

Constructor args: `0x626972640a000000000000000000000000000000000000000000000000000000626972640a000000000000000000000000000000000000000000000000000000` (bird, bird)

Token page showing `bird bird`:
https://rinkeby.etherscan.io/token/0x5Fe371CcB3C0dc8718B7c0470600A230d6c2eB45
